apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
