apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32107
      protocol: TCP
