apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # This should match the label in the deployment spec
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service
      targetPort: 80     # Port the Nginx container listens on
  type: LoadBalancer    # Change to 'NodePort' if you don't want a load balancer, or to expose it differently
