# Deployment fileee

name: Deploy tomcat to EKS

on:
  push:
    branches: 
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: kube

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          EKS_CLUSTER_NAME: ${{ env.EKS_CLUSTER_NAME }}
        run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME


      - name: Deploy tomcat app
        run: |
          kubectl apply -f dep.yaml
          kubectl apply -f svc.yaml

      - name: Verify deployment rollout
        run: |
          kubectl rollout status deployment/dep

      - name: List pods
        run: |
          kubectl get pods -o wide
